### ISSUE TITLE
Task ordering

### ISSUE THREAD

**Issue by BoD** [blundell/release-android-library#1]
I am not sure this is really a bug, and I must admit I haven't tried your gradle script yet. But reading the source, I am wondering:
Shouldn't you put `zipRelease.mustRunAfter uploadArchives` somewhere?  I have the impression that with the current code, the zipping could happen before the 'mavening'.

**Comment by blundell** [comment]
I'd recommend moving to using this plugin now: https://github.com/novoda/bintray-release

this script is unsupported
