### ISSUE TITLE
As of gradle build 3.0.1 and buildToolVersion 27 there's no zip

### ISSUE THREAD

**Issue by catennacio** [blundell/release-android-library#17]
Can't find the release-${version} in the build folder. What could go wrong?

**Comment by blundell** [comment]
I'd recommend moving to using this plugin now: github.com/novoda/bintray-release 

this script is unsupported

**Comment by accuware** [comment]
Too bad. I was very happy with this solution. The bintray-release script seems to be bloated and gives you less control
