### ISSUE TITLE
Bintray error - Add a POM file to the latest version of your package

### ISSUE THREAD

**Issue by rankorn** [blundell/release-android-library#3]
I am trying to use your remote gradle script and it seems to work great. 
A zip file is created with the structure as described in the blog post.

But when I try to add my package to JCenter (manually from the Bintray site) I get the 
"Add a POM file to the latest version of your package"
error.

I can see the pom inside the zip but still something is wrong.. maybe the name of the pom file?
Any help will be appreciated

**Comment by mrkcsc** [comment]
Use the non-zipped output or select "explode output" checkbox in the JCenter UI if you are using it.

**Comment by rankorn** [comment]
Thanks @mrkcsc, using the checkbox does the trick.

**Comment by brucetoo** [comment]
select "explode output" checkbox in the JCenter UI  ? sorry  i can not find it . Help ,please..
