### ISSUE TITLE
Gradle plugin 1.1.0 -- Cannot call getBootClasspath() before setTargetInfo() is called

### ISSUE THREAD

**Issue by mattlogan** [blundell/release-android-library#6]
I'm having an issue syncing my project with my gradle files.

Here's my library module's `build.gradle` file:

```groovy
apply plugin: 'com.android.library'

ext {
    PUBLISH_GROUP_ID = 'me.mattlogan.artiste'
    PUBLISH_ARTIFACT_ID = 'artiste'
    PUBLISH_VERSION = '2.0.1'
}

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

    defaultConfig {
        minSdkVersion 10
        targetSdkVersion 21
        versionCode 2
        versionName "2.0.1"
    }
}

apply from: 'https://raw.githubusercontent.com/blundell/release-android-library/master/android-release-aar.gradle'
```

When I try to sync my project, I see the following error:

![screen shot 2015-02-22 at 2 56 32 pm](https://cloud.githubusercontent.com/assets/4635072/6321010/60f57cf2-baa3-11e4-9fb0-d8a1882dd643.png)

This is definitely caused by the `android-release-aar` task, as the error goes away when I comment out that line.

**Comment by mattlogan** [comment]
Pull request: https://github.com/blundell/release-android-library/pull/7

**Comment by JaySoyer** [comment]
Note: This is actually a bug in com.android.tools.build:gradle:1.1.0.  Using a higher version (as of this comment) 1.1.3 resolves the issue as well.

**Comment by spuchetavm** [comment]
Watch all of your build.gradle files, including the node_modules ones. buildToolsVersion and compileSdkVersion must match in all of them.
