### ISSUE TITLE
Include local project library

### ISSUE THREAD

**Issue by HugoGresse** [blundell/release-android-library#8]
I have a project library included in my library. Is there a way to have it include in the release ? 

Just to be clear, how will gradle manage library dependencies like  compile 'com.squareup.picasso:picasso:2.5.0' ? Will gradle download it ?

**Comment by blundell** [comment]
No you cannot include dependencies (as source code or jars) in the release, however it will be handled and downloaded as an external dependency.

**Comment by HugoGresse** [comment]
thank you for your answer. Closing issue
